---
galaxy_info:
  author: Chun Pan Yung
  description: Setup and configure WSL

  license: MIT

  min_ansible_version: "2.14"

  platforms:
    - name: Debian
      versions:
        - all

  galaxy_tags: []

dependencies: []
