# SPDX-License-Identifier: MIT-0
---
# tasks file for golang
- name: Install Go programming language
  become: true
  when: ansible_os_family != 'Alpine'
  ansible.builtin.package:
    name: golang
  notify: Change GOPATH

- name: Install Go programming language for Alpine
  become: true
  when: ansible_os_family == 'Alpine'
  community.general.apk:
    name: go
  notify: Change GOPATH

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Install task
  ansible.builtin.command:
    cmd: go install github.com/go-task/task/v3/cmd/task@latest
  register: __command
  # changed_when: __command.stdout is search("Appended new lines*")
  changed_when: __command.stdout is search("go\:*")

- name: Setup GO environment variables
  ansible.builtin.blockinfile:
    create: true
    backup: true
    mode: '0644'
    path: "{{ ansible_user_dir }}/.bashrc"
    insertbefore: "export PATH"
    marker: "# {mark} SETUP GO PATH"
    block: |
      if ! [[ "$PATH" =~ $HOME/.go/bin: ]] ; then
        PATH="$HOME/.go/bin:$PATH"
      fi
