---
# tasks file for ansi_colle.linux.fish
- name: Install utilities for all alpine, RedHat, and Debian distro
  become: true
  ansible.builtin.package:
    name: fish

- name: Install fisher plugin manager
  vars:
    link: https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish
  ansible.builtin.shell:
    executable: /usr/bin/env fish
    cmd: |
      set -o pipefail
      curl -sL {{ link }} | source && fisher install jorgebucaran/fisher
    creates: "{{ ansible_user_dir }}/.config/fish/functions/fisher.fish"
