---
# tasks file for arkade
- name: Retrieve information from github api
  ansible.builtin.uri:
    url: "https://api.github.com/repos/alexellis/arkade/releases/latest"
    return_content: true
  register: arkade_api

- name: Compare to current arkade version if it exists
  ansi_colle.mods.cmp_pkg:
    name: arkade
    version_arg: version
    desired_version: "{{ arkade_api.json.tag_name }}"
  register: arkade_cmp

- name: Execute the following if version is not the latest
  when: (arkade_cmp.rc == 2) or (arkade_cmp.rc ==1)
  block:
    - name: Ensure directory exists
      ansible.builtin.file:
        path: /usr/local/bin/
        state: directory
        mode: '0755'

    - name: Download executables for linux x64 system
      ansible.builtin.get_url:
        url: "{{ arkade_api.json.assets[0].browser_download_url }}"
        dest: "/usr/local/bin/"
        mode: '0755'
