---
### REQUIRED
namespace: ansi_colle
name: linux
version: 1.1.0
readme: README.md
authors:
  - Chun Pan Yung <31672021+ChunPanYung@users.noreply.github.com>

repository: http://example.com/repository

description: your collection description
license:
  - GPL-2.0-or-later

dependencies: {}

tags:
  - linux
  - tools
