[project]
name = "ansi_colle-linux"
dynamic = ["version"]
description = "Default template for PDM package"
authors = [
    {name = "Chun Pan Yung", email = "31672021+ChunPanYung@users.noreply.github.com"},
]
dependencies = [
    "ansible>=9.2.0",
    "tomli-w>=1.0.0",
]
requires-python = ">=3.11"
readme = "README.md"
license = {text = "MIT"}

[tool.pdm]
distribution = false

[tool.pdm.scripts]
install = "ansible-playbooks ansi_colle.linux.install"

[tool.pdm.version]
source = "call"
getter = "py.util.get_version"
