---
# Required by GitHub Action to install additional collection and roles.
collections:
  - name: community.general
    version: "*"

  - name: https://github.com/ChunPanYung/ansi_colle-mods.git
    type: git
    version: main
