---
- name: Install Rust and library
  block:
    - name: Install Rust, package manager and format tool
      become: true
      ansible.builtin.apt:
        name:
          - rustc
          - cargo
          - rustfmt
