---
- name: Execute installation with sudo
  become: true
  block:
    - name: Install utilities
      ansible.builtin.dnf:
        name:
          - tmux
          - git
          - git-lfs

- name: Install packages from repository
  become: true
  block:
    - name: Install dnf-plugins-core, required by community.general.copr
      ansible.builtin.dnf:
        name: dnf-plugins-core

    - name: Enable lazygit repository
      community.general.copr:
        name: 'atim/lazygit'

    - name: Install utilities
      ansible.builtin.dnf:
        name: lazygit
