---
# linux -> dev_tools/tasks/
- name: Install utilities for Debian and Fedora
  become: true
  when: ansible_os_family != 'Alpine'
  ansible.builtin.package:
    name:
      - fd-find

- name: Install utilties for Alpine Linux
  become: true
  when: ansible_os_family == 'Alpine'
  community.general.apk:
    name:
      - fd

- name: Install utilities for all alpine, RedHat, and Debian distro
  become: true
  ansible.builtin.package:
    name:
      - shellcheck
      - shfmt
      - ripgrep

- name: Install container tools
  become: true
  ansible.builtin.package:
    name:
      - buildah
      - podman

- name: Import tasks if it is RedHat based system
  ansible.builtin.import_tasks: _fedora.yml
  when: ansible_os_family == 'RedHat'

- name: Import tasks if it is RedHat based system
  ansible.builtin.import_tasks: _gpg.yml
