---
# linux -> dev_tools/tasks/
- name: Install utilities
  become: true
  ansible.builtin.package:
    name:
      - fd-find
      - ripgrep

- name: Import tasks if it is Debian based system
  ansible.builtin.import_tasks: _debian.yml
  when: ansible_os_family == 'Debian'

- name: Import tasks if it is RedHat based system
  ansible.builtin.import_tasks: _fedora.yml
  when: ansible_os_family == 'RedHat'
