---
- name: Install npm for non RedHat based OS
  become: true
  when: ansible_os_family != 'Redhat'
  ansible.builtin.package:
    name: npm

- name: Install utilties for RedHat based OS
  become: true
  when: ansible_os_family == 'RedHat'
  ansible.builtin.package:
    name: nodejs-npm

- name: Create npm configuration file, do not change times to make it idempotent
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.npmrc"
    mode: '0644'
    state: touch
    modification_time: preserve
    access_time: preserve

- name: Setup global package directory for npm
  ansible.builtin.lineinfile:
    path: "{{ ansible_user_dir }}/.npmrc"
    regexp: '^prefix='
    line: "prefix={{ ansible_user_dir }}/.npm-global"

- name: Setup PATH for npm for Debian based OS
  when: ansible_os_family == 'Debian'
  ansible.builtin.blockinfile:
    path: "{{ ansible_user_dir }}/.profile"
    insertbefore: "^export PATH"
    marker: "# {mark} SETUP NPM PATH"
    block: |
      if [ -d "$HOME/.npm-global/bin" ] ; then
          PATH="$HOME/.npm-global/bin:$PATH"
      fi

- name: Setup PATH for npm
  when: ansible_os_family == 'RedHat'
  ansible.builtin.blockinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    insertbefore: "^export PATH"
    marker: "# {mark} SETUP NPM PATH"
    block: |
      if ! [[ "$PATH" =~ $HOME/.npm-global/bin: ]]
      then
        PATH="$HOME/.npm-global/bin:$PATH"
      fi

- name: Install Shell LSP
  community.general.npm:
    name: bash-language-server
    global: true

