---
# tasks file for pipx
- name: Install python and related packages
  ansible.builtin.package:
    name:
      - python3-pip
      - pipx
      - python3-ipython

- name: Create venv directory for pip virtual environment
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.venv/"
    mode: '0755'
    state: directory

- name: Install developmental tools
  become: false
  community.general.pipx:
    name: "{{ item }}"
  loop:
    - git-cliff
    - ruff-lsp
    - black
    - pytest
    - pre-commit
    - pdm
