---
# linux -> home_config/tasks
- name: Create $HOME/.local/state for XDG_STATE_HOME
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.local/state"
    state: directory
    mode: '0755'

- name: Ensure private directory on keys and secrets
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0700'
  loop:
    - "{{ ansible_user_dir }}/.ssh"
    - "{{ ansible_user_dir }}/.gnupg"
    - "{{ ansible_user_dir }}/.keys"

- name: Create directory for git repo
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/Repos/"
    state: directory
    mode: '0755'

- name: Create directory for binary, exeuctables, and scripts
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.local/bin/"
    state: directory
    mode: '0755'

- name: Setup 'inputrc' dot file
  ansible.builtin.lineinfile:
    path: "{{ ansible_user_dir }}/.inputrc"
    line: "{{ item }}"
    create: true
    mode: '0644'
  loop:
    - '# Ctrl-Backspace: delete previous word'
    - '"\C-H": shell-backward-kill-word'

- name: Customize git configuration
  block:
    - name: Create git directory
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/.config/git/"
        mode: '0755'
        state: directory

    - name: Add line to gitignore file
      ansible.builtin.lineinfile:
        path: "{{ ansible_user_dir }}/.config/git/ignore"
        line: ".directory"
        create: true
        mode: '0644'

    - name: Global gitignore file
      ansible.builtin.copy:
        src: gitignore
        dest: "{{ ansible_user_dir }}/.gitignore"
        mode: '0644'

    - name: Setup gitconfig
      ansible.builtin.blockinfile:
        path: "{{ ansible_user_dir }}/.gitconfig"
        append_newline: true
        prepend_newline: true
        block: "{{ lookup('ansible.builtin.file', 'gitconfig') }}"

- name: Setup environment variable on profile on RedHat
  when: ansible_os_family == 'RedHat'
  ansible.builtin.blockinfile:
    path: "{{ ansible_user_dir }}/.bash_profile"
    append_newline: true
    prepend_newline: true
    marker: "# {mark} PERSONALIZE BASH"
    block: |
      export XDG_CONFIG_HOME="$HOME/.config"
      export XDG_CACHE_HOME="$HOME/.cache"
      export XDG_DATA_HOME="$HOME/.local/share"
      export XDG_STATE_HOME="$HOME/.local/state"
      export RAM="/tmp/RAM"
      # Setup editor
      export EDITOR="/usr/bin/env nvim"
      export SYSTEMD_EDITOR="/usr/bin/env nvim"

- name: Personalize bash
  ansible.builtin.blockinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    append_newline: true
    prepend_newline: true
    marker: "# {mark} PERSONALIZE BASH"
    block: |
      # Do not add space after autocompletion for 'ls' command
      compopt -o nospace ls
      # can't use it directly with compopt
      complete -o nospace -F _longopt source
