---
galaxy_info:
  author: Chun Pan Yung
  description: >
    Install and configure ergo, management of multiple apps running
    different ports.

  license: MIT

  min_ansible_version: "2.15"

  platforms:
    - name: Fedora
      versions:
        - all

  galaxy_tags: []

dependencies:
  - ansi_colle.linux.home_config
