---
- name: Install packages for debian
  become: true
  ansible.builtin.apt:
    name:
      - pipx

- name: Install uv package and project manager
  community.general.pipx:
    name: uv
    state: latest

- name: Expose 3000 port for development
  become: true
  community.general.ufw:
    rule: allow
    port: 3000
    proto: tcp
    state: enabled
