---
# linux -> dev_tools/tasks/
- name: Install packages across OS
  become: true
  ansible.builtin.package:
    name:
      - fd-find

- name: Install utilities for all alpine, RedHat, and Debian distro
  become: true
  ansible.builtin.package:
    name:
      - shellcheck
      - shfmt
      - ripgrep
      - git

- name: Install container tools
  become: true
  ansible.builtin.package:
    name:
      - buildah
      - podman
  notify:
    - Enable podman.socket on user scope

- name: Create DOCKER_HOST environment variable
  ansible.builtin.lineinfile:
    create: true
    backup: true
    mode: '0644'
    path: "{{ ansible_user_dir }}/.bashrc"
    regexp: '^DOCKER_HOST='
    line: >
      DOCKER_HOST="$(podman info --format '{{ '{{' }}.Host.RemoteSocket.Path{{ '}}' }}')"
      && export DOCKER_HOST

- name: Import tasks if it is RedHat based system
  ansible.builtin.import_tasks: _fedora.yml
  when: ansible_os_family == 'RedHat'

- name: Import tasks if it is Debian based system
  ansible.builtin.import_tasks: _debian.yml
  when: ansible_os_family == 'Debian'

- name: Configure GnuPG
  ansible.builtin.import_tasks: _gpg.yml
