---
# tasks file for lang
- name: Install rust and package manager
  become: true
  ansible.builtin.package:
    name: cargo

- name: Setup rust environment variables
  ansible.builtin.blockinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    insertbefore: "export PATH"
    marker: "# {mark} SETUP RUST PATH"
    block: |
      if ! [[ "$PATH" =~ $HOME/.cargo/bin: ]] ; then
        PATH="$HOME/.cargo/bin:$PATH"
      fi
