---
# tasks file for ansible
- name: Install ansible
  become: true
  ansible.builtin.package:
    name: ansible

- name: Install ansible-language-server from npm
  community.general.npm:
    name: "@ansible/ansible-language-server"
    global: true

- name: Install ansible molecule
  become: true
  ansible.builtin.dnf:
    name: python3-molecule
