---
# tasks file for ansible
- name: Install ansible
  become: true
  ansible.builtin.package:
    name: ansible

- name: Setup ansible configuration
  become: true
  community.general.ini_file:
    path: /etc/ansible/ansible.cfg
    section: defaults
    option: "{{ item.key }}"
    value: "{{ item.value }}"
    mode: '0644'
  loop:
    - {key: 'callback_result_format', value: 'yaml'}
    - {key: 'verbosity', value: '1'}
