---
- name: Execute on localhost
  hosts: all
  # vars_prompt:
  #   - name: ansible_become_password
  #     prompt: "BECOME password"

  roles:
    - role: ansi_colle.slim_os.fedora
      tags: fedora
    - role: ansi_colle.linux.npm
      tags: npm
    - role: ansi_colle.linux.home_config
      tags: home_config
    - role: ansi_colle.linux.flatpak
      tags: flatpak
    - role: ansi_colle.linux.systemd
      tags: systemd
    - role: ansi_colle.linux.ansible
      tags: ansible
    - role: ansi_colle.linux.dev_tools
      tags: dev_tools
    - role: ansi_colle.linux.kopia
      tags: kopia
    - role: ansi_colle.linux.sys_config
      tags: sys_config
    - role: ansi_colle.linux.ergo
      tags: ergo
    - role: ansi_colle.linux.arkade
      tags: arkade
