---
galaxy_info:
  author: Chun Pan Yung
  description: Install and setup go programming language

  license: MIT

  min_ansible_version: "2.16"

  platforms:
    - name: Fedora
      versions:
        - all

  galaxy_tags: []

dependencies: []
