---
galaxy_info:
  author: Chun Pan Yung
  description: Install Arkade package manager for developer.

  license: MIT

  min_ansible_version: "2.14"

  platforms:
    - name: Fedora
      versions:
        - all

  galaxy_tags: []

dependencies: []
