---
# tasks file for wsl
- name: Ensure bash_aliases present
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.bash_aliases"
    state: touch
    mode: '0644'
    modification_time: preserve
    access_time: preserve

# - name: Enable ssh-agent and ssh-add
#   ansible.builtin.lineinfile:
#     path: "{{ ansible_user_dir }}/.bashrc"
#     regexp: '^eval $(ssh-agent -s)'
#     line: 'eval $(ssh-agent -s)'

- name: Install
  become: true
  ansible.builtin.package:
    name: keychain

- name: Setup pinentry for GPG
  become: true
  when: ansible_os_family == 'Debian'
  block:
    - name: Update to use pinentry-tty
      community.general.alternatives:
        name: pinentry
        path: /usr/bin/pinentry-tty
