---
- name: Setup bash profile
  ansible.builtin.blockinfile:
    path: "{{ ansible_user_dir }}/.bash_profile"
    block: "{{ lookup('ansible.builtin.file', 'profile.sh') }}"
    insertafter: "EOF"

- name: Create bashrc.d directory
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.bashrc.d"
    state: directory
    mode: '0755'

- name: Setup bash aliases
  ansible.builtin.blockinfile:
    path: "{{ ansible_user_dir }}/.bashrc.d/aliases.bash"
    append_newline: true
    prepend_newline: true
    marker: "# {mark} SETUP COMMON ALIASES"
    block: |
      alias less='less --raw-control-chars'
      alias python='python3'

- name: Setup opt PATH
  ansible.builtin.blockinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    insertbefore: "^export PATH"
    marker: "# {mark} SETUP OPT PATH"
    block: |
      if ! [[ "$PATH" =~ $HOME/.local/opt: ]]
      then
        PATH="$HOME/.local/opt:$PATH"
      fi

- name: Setup script PATH
  ansible.builtin.blockinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    insertbefore: "^export PATH"
    marker: "# {mark} SETUP SCRIPT PATH"
    block: |
      if ! [[ "$PATH" =~ $HOME/.local/script: ]]
      then
        PATH="$HOME/.local/script:$PATH"
      fi
