---
# linux -> home_config/tasks
- name: Create $HOME/.local/state for XDG_STATE_HOME
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.local/state"
    state: directory
    mode: '0755'

- name: Ensure private directory on keys and secrets
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0700'
  loop:
    - "{{ ansible_user_dir }}/.ssh"
    - "{{ ansible_user_dir }}/.gnupg"
    - "{{ ansible_user_dir }}/.keys"

- name: Create directory for git repo
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/Repos/git/"
    state: directory
    mode: '0755'

- name: Create directory for binary, exeuctables, and scripts
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ ansible_user_dir }}/.local/bin/"
    - "{{ ansible_user_dir }}/.local/opt/"
    - "{{ ansible_user_dir }}/.local/script/"

- name: Create directory for local systemd
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/systemd/user/"
    state: directory
    mode: '0750'

- name: Customize git configuration
  block:
    - name: Default gitconfig file
      ansible.builtin.blockinfile:
        path: "{{ ansible_user_dir }}/.gitconfig"
        block: "{{ lookup('ansible.builtin.file', 'gitconfig') }}"

    - name: Global gitignore file
      ansible.builtin.copy:
        src: gitignore
        dest: "{{ ansible_user_dir }}/.gitignore"
        mode: '0644'

- name: Personalize bash
  ansible.builtin.blockinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    marker: "# {mark} PERSONALIZE BASH"
    block: |
      # Do not add space after autocompletion for 'ls' command
      compopt -o nospace ls
      # can't use it directly with compopt
      complete -o nospace -F _longopt source

- name: Execute tasks specific to RedHat based OS
  ansible.builtin.include_tasks:
    file: _redhat.yml
  when: ansible_os_family == 'RedHat'
