---
- name: Install collections and roles
  hosts: localhost
  connection: local
  tasks:
    - name: Install community collections
      community.general.ansible_galaxy_install:
        type: collection
        name: "{{ item }}"
      loop:
        - community.general
        - containers.podman

    - name: Install custom collections
      community.general.ansible_galaxy_install:
        type: collection
        name: "{{ item }}"
      loop:
        - git+https://github.com/ChunPanYung/ansi_colle-mods.git,main
        - git+https://github.com/ChunPanYung/ansi_colle-slim_os.git,main
        - git+https://github.com/ChunPanYung/ansi_colle-server.git,main

    - name: Install this collection
      vars:
        this_collection: git+https://github.com/ChunPanYung/ansi_colle-linux.git
      community.general.ansible_galaxy_install:
        type: collection
        name: "{{ this_collection }},{{ git_branch | default('main') }}"
