---
- name: Execute on localhost (WSL)
  hosts: wsl
  vars_prompt:
    - name: ansible_become_pass
      prompt: "BECOME password"

  roles:
    - role: ansi_colle.linux.home
      tags: home
    - role: ansi_colle.linux.ansible
      tags: ansible
    - role: ansi_colle.linux.development
      tags: development
    - role: ansi_colle.linux.wsl
      tags: wsl
